spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.43.132/sell?characterEncoding=utf-8&useSSL=false
    #password: 123456
    #url: jdbc:mysql://192.168.0.113/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.43.132
    port: 6379
  mvc:
    view:
      #prefix: classpath:/templates/
      #suffix: .ftl

#    hibernate:
#      ddl-auto: update
server:
  context-path: /
  port: 80

logging:
  level:
    com.imooc.dataobject.mapper: trace
#  pattern:
#    console: "%d - %msg%n"
#  #path: E:/workspace/r1l5jr/log
#  file: E:/workspace/r1l5jr/log/sell.log
#  level:
#    com.imooc.LoggerTest: debug


projectUrl:
  wechatMpAuthorize: http://ssss.com
  wechatOpenAuthorize: http://ssss.com
  sell: http://localhost
mybatis:
  mapper-locations: classpath:mapper/*.xml

